version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

  http-server:
    build:
      context: .
      dockerfile: docker/dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - DB_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      - postgres
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: docker/dockerfile.frontend
  #     args:
  #       - DB_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DB_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
  #   depends_on:
  #     - postgres
volumes:
  pg_data:
