FROM node:20-alpine


RUN npm install -g pnpm


WORKDIR /app


COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY packages ./packages

COPY apps/http-server ./apps/http-server


RUN pnpm install


RUN pnpm run db:generate


EXPOSE 3001

CMD ["pnpm", "run", "start:backend"]
