name : depoly backend to EC2
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: clone repo
              uses: actions/checkout@v5
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                context: .
                file: ./docker/dockerfile.backend
                push: true
                tags: harsharora17/my_backend:${{ github.sha }}
            - name: Authorize SSH Connections
              uses: mnavarrocarter/authorize-aws-security-group-ingress-action@v1.0.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: 'us-east-1'
                aws-security-group-id: ${{ secrets.AWS_SSH_SECURITY_GROUP_ID }}
                protocol: 'tcp'
                port: ${{ secrets.PORT }}

            - name: Execute remote SSH commands using SSH key
              uses: LuisEnMarroquin/setup-ssh-action@v3.0.0 
              with:
                ORIGIN: ${{ secrets.HOST }}
                USER: ${{ secrets.USERNAME }}
                SSHKEY: ${{ secrets.KEY }}
                PORT: ${{ secrets.PORT }}
            - run: echo hello
         


